# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yamaurakazuki/Lecture/3rd/COJT/TachometerAPI/web_tachometer_demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yamaurakazuki/Lecture/3rd/COJT/TachometerAPI/web_tachometer_demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yamaurakazuki/Lecture/3rd/COJT/TachometerAPI/web_tachometer_demo/CMakeFiles /Users/yamaurakazuki/Lecture/3rd/COJT/TachometerAPI/web_tachometer_demo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yamaurakazuki/Lecture/3rd/COJT/TachometerAPI/web_tachometer_demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named websocketpp

# Build rule for target.
websocketpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 websocketpp
.PHONY : websocketpp

# fast build rule for target.
websocketpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocketpp.dir/build.make CMakeFiles/websocketpp.dir/build
.PHONY : websocketpp/fast

#=============================================================================
# Target rules for targets named udpToWsConverter

# Build rule for target.
udpToWsConverter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 udpToWsConverter
.PHONY : udpToWsConverter

# fast build rule for target.
udpToWsConverter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpToWsConverter.dir/build.make CMakeFiles/udpToWsConverter.dir/build
.PHONY : udpToWsConverter/fast

#=============================================================================
# Target rules for targets named serialToUdpConverter

# Build rule for target.
serialToUdpConverter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serialToUdpConverter
.PHONY : serialToUdpConverter

# fast build rule for target.
serialToUdpConverter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialToUdpConverter.dir/build.make CMakeFiles/serialToUdpConverter.dir/build
.PHONY : serialToUdpConverter/fast

#=============================================================================
# Target rules for targets named daemonUdpToWsConverter

# Build rule for target.
daemonUdpToWsConverter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 daemonUdpToWsConverter
.PHONY : daemonUdpToWsConverter

# fast build rule for target.
daemonUdpToWsConverter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daemonUdpToWsConverter.dir/build.make CMakeFiles/daemonUdpToWsConverter.dir/build
.PHONY : daemonUdpToWsConverter/fast

daemonUdpToWsConverter.o: daemonUdpToWsConverter.cpp.o
.PHONY : daemonUdpToWsConverter.o

# target to build an object file
daemonUdpToWsConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daemonUdpToWsConverter.dir/build.make CMakeFiles/daemonUdpToWsConverter.dir/daemonUdpToWsConverter.cpp.o
.PHONY : daemonUdpToWsConverter.cpp.o

daemonUdpToWsConverter.i: daemonUdpToWsConverter.cpp.i
.PHONY : daemonUdpToWsConverter.i

# target to preprocess a source file
daemonUdpToWsConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daemonUdpToWsConverter.dir/build.make CMakeFiles/daemonUdpToWsConverter.dir/daemonUdpToWsConverter.cpp.i
.PHONY : daemonUdpToWsConverter.cpp.i

daemonUdpToWsConverter.s: daemonUdpToWsConverter.cpp.s
.PHONY : daemonUdpToWsConverter.s

# target to generate assembly for a file
daemonUdpToWsConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/daemonUdpToWsConverter.dir/build.make CMakeFiles/daemonUdpToWsConverter.dir/daemonUdpToWsConverter.cpp.s
.PHONY : daemonUdpToWsConverter.cpp.s

serialToUdpConverter.o: serialToUdpConverter.cpp.o
.PHONY : serialToUdpConverter.o

# target to build an object file
serialToUdpConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialToUdpConverter.dir/build.make CMakeFiles/serialToUdpConverter.dir/serialToUdpConverter.cpp.o
.PHONY : serialToUdpConverter.cpp.o

serialToUdpConverter.i: serialToUdpConverter.cpp.i
.PHONY : serialToUdpConverter.i

# target to preprocess a source file
serialToUdpConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialToUdpConverter.dir/build.make CMakeFiles/serialToUdpConverter.dir/serialToUdpConverter.cpp.i
.PHONY : serialToUdpConverter.cpp.i

serialToUdpConverter.s: serialToUdpConverter.cpp.s
.PHONY : serialToUdpConverter.s

# target to generate assembly for a file
serialToUdpConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serialToUdpConverter.dir/build.make CMakeFiles/serialToUdpConverter.dir/serialToUdpConverter.cpp.s
.PHONY : serialToUdpConverter.cpp.s

udpToWsConverter.o: udpToWsConverter.cpp.o
.PHONY : udpToWsConverter.o

# target to build an object file
udpToWsConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpToWsConverter.dir/build.make CMakeFiles/udpToWsConverter.dir/udpToWsConverter.cpp.o
.PHONY : udpToWsConverter.cpp.o

udpToWsConverter.i: udpToWsConverter.cpp.i
.PHONY : udpToWsConverter.i

# target to preprocess a source file
udpToWsConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpToWsConverter.dir/build.make CMakeFiles/udpToWsConverter.dir/udpToWsConverter.cpp.i
.PHONY : udpToWsConverter.cpp.i

udpToWsConverter.s: udpToWsConverter.cpp.s
.PHONY : udpToWsConverter.s

# target to generate assembly for a file
udpToWsConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/udpToWsConverter.dir/build.make CMakeFiles/udpToWsConverter.dir/udpToWsConverter.cpp.s
.PHONY : udpToWsConverter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... websocketpp"
	@echo "... daemonUdpToWsConverter"
	@echo "... serialToUdpConverter"
	@echo "... udpToWsConverter"
	@echo "... daemonUdpToWsConverter.o"
	@echo "... daemonUdpToWsConverter.i"
	@echo "... daemonUdpToWsConverter.s"
	@echo "... serialToUdpConverter.o"
	@echo "... serialToUdpConverter.i"
	@echo "... serialToUdpConverter.s"
	@echo "... udpToWsConverter.o"
	@echo "... udpToWsConverter.i"
	@echo "... udpToWsConverter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

